'use strict';
// desc: write this session's tool instructions into AGENTS.md
// usage: leo agents            print the block
//        leo agents --list     the inventory, for a human
//        leo agents --ask      the question to put to the developer
//        leo agents --auto     write the block into AGENTS.md
//        leo agents --check    does the block describe this session?

const fs = require('fs');
const path = require('path');
const { say, info, dim, ok, warn, err, die, head_, LeoExit } = require('../lib/ui');
const { needRepo } = require('../lib/ctx');
const { isFile, readIfFile, writeAtomic } = require('../lib/fsx');
const caps = require('../lib/caps');

const BEGIN = '<!-- leo:tools begin';
const END = '<!-- leo:tools end -->';

// block — the generated section. Everything in it is derived: the mode, the
// switches, what is installed, what each adapter says about itself. Nothing
// is stored to make it printable, which is why regenerating it can never
// disagree with `leo session`.
function block(ctx, adapters, fp) {
  const out = [];
  const w = (s) => out.push(s);

  w(BEGIN + ' fingerprint=' + fp + ' -->');
  w('<!-- Generated by `leo agents`. Do not edit: run it again. -->');
  w('');
  w('## Tools this session');
  w('');

  if (!ctx.mode) {
    w('No session declared, so nothing is on or off.');
    w('Ask the developer for one: `leo session --mode coding`.');
    w('Until then, announce anything you use with `leo use <name>`.');
    w('');
    w(END);
    return out.join('\n') + '\n';
  }

  // Names and pointers, not a table.
  //
  // This block used to be a four-column table with a row per capability: 19
  // lines, in the one file that is re-read on every request of every session
  // forever. It pushed a fresh AGENTS.md to 81 lines against its own 70-line
  // budget, and every one of those lines was a restatement of something
  // already written down in `.leo/tools/<name>.md`.
  //
  // So this says which tools are on, which are off, and where the detail
  // lives. The agent needs the switch positions on every request; it needs
  // the instructions only when it is about to use one, and that is a file
  // read away.
  const list = caps.capsList(adapters);
  const on = [], off = [], missing = [];
  for (const c of list) {
    const label = caps.capLabel(adapters, c);
    if (caps.capState(ctx, adapters, c) === 'on') {
      on.push(label);
      if (caps.capPresent(ctx, adapters, c) === 1) missing.push(c);
    } else {
      off.push(label);
    }
  }

  // Facts that change, and nowhere else to find them. The rules for USING a
  // tool -- announce it, never install it, OFF is the developer's -- are
  // standing orders in the template above and do not change per session, so
  // restating them here would be paying for them twice on every request.
  w('Mode **' + ctx.mode + '**. ON: ' + (on.length ? on.join(', ') : 'nothing') + '.');
  w('OFF: ' + (off.length ? off.join(', ') : 'nothing') + '.');
  if (missing.length) {
    w('Not installed: ' + missing.join(', ') + ' — tell them `leo install <name>`.');
  }
  w('');
  w('Read on demand, never import here: a tool is `.leo/tools/<name>.md`, the');
  w('loop is `.leo/workflow.md`, the grill is `.leo/skills/grilling/SKILL.md`.');
  w('');
  w(END);
  return out.join('\n') + '\n';
}

// isCurrent — does AGENTS.md's stamped fingerprint match this session?
// Exported because `leo session` asks the same question and shelling out to
// `leo agents --check` to find out would be a process spawn per report.
function isCurrent(ctx, adapters) {
  const body = readIfFile(path.join(ctx.root, 'AGENTS.md'));
  if (body === null) return false;
  const m = new RegExp(BEGIN + ' fingerprint=([a-z0-9]*)').exec(body);
  if (!m) return false;
  return m[1] === caps.capFingerprint(ctx, adapters);
}

function run(ctx) {
  needRepo(ctx);
  const adapters = ctx.adapters || caps.loadAdapters(ctx);
  ctx.adapters = adapters;
  const agentsFile = path.join(ctx.root, 'AGENTS.md');
  const list = caps.capsList(adapters);

  let mode = 'show';
  for (const a of ctx.argv) {
    if (a === '--auto') mode = 'auto';
    else if (a === '--ask') mode = 'ask';
    else if (a === '--list') mode = 'list';
    else if (a === '--check') mode = 'check';
    else if (a[0] === '-') die('unknown option: ' + a + '  (--auto --ask --list --check)');
    else die('unexpected argument: ' + a);
  }

  // Computed once, at the top of the run, and used everywhere below. Calling
  // it twice would be the obvious thing and would be wrong: writing the block
  // changes AGENTS.md, and an adapter is allowed to detect itself by reading
  // AGENTS.md -- ponytail does. Two calls straddling the write can therefore
  // disagree, and the block would be stamped with a fingerprint that was
  // already out of date before the file was closed.
  const FP = caps.capFingerprint(ctx, adapters);

  if (mode === 'list') {
    head_('tools leo knows');
    info('  ' + 'TOOL'.padEnd(12) + ' ' + 'STATE'.padEnd(5) + ' ' +
      'INSTALLED'.padEnd(10) + ' ' + 'KIND'.padEnd(9) + ' MCP');
    for (const c of list) {
      const rc = caps.capPresent(ctx, adapters, c);
      const inst = rc === 0 ? 'yes' : (rc === 1 ? 'NO' : 'no-adapter');
      const m = caps.capMcp(adapters, c) || '-';
      info('  ' + c.padEnd(12) + ' ' + caps.capState(ctx, adapters, c).padEnd(5) + ' ' +
        inst.padEnd(10) + ' ' + caps.capKind(adapters, c).padEnd(9) + ' ' + m);
    }
    process.stderr.write('\n');
    dim('  leo agents --ask    put the choice to the developer');
    dim("  leo agents --auto   take the mode's defaults and write AGENTS.md");
    return 0;
  }

  if (mode === 'ask') {
    // leo prints the question; it does not ask, and it does not act on an
    // answer it never heard.
    if (!ctx.mode) {
      warn('no session yet — the mode decides the defaults');
      dim('  ask for one first: leo session --mode coding');
    }
    head_('ask the developer this, before you touch anything');
    info('');
    info('  These tools are available in this repository. Which do you want');
    info('  enabled for this session?');
    info('');
    for (const c of list) {
      const rc = caps.capPresent(ctx, adapters, c);
      const inst = rc === 0 ? 'installed'
        : (rc === 1 ? 'NOT installed — leo install ' + c : 'leo cannot tell');
      info('    ' + c.padEnd(12) + ' ' + caps.capState(ctx, adapters, c).padEnd(4) + '  ' + inst);
      const one = caps.capOneline(adapters, c, ctx);
      if (one) info('                 ' + one);
    }
    dim('  They said keep the defaults? Then: leo agents --auto');
    return 0;
  }

  if (mode === 'check') {
    // The gate. A block that describes a session that no longer exists is
    // worse than no block: the agent reads it, believes it, and uses a tool
    // the developer switched off an hour ago.
    if (!isFile(agentsFile)) die('no AGENTS.md — run: leo init');
    const body = readIfFile(agentsFile) || '';
    if (body.indexOf(BEGIN) === -1) {
      err('AGENTS.md has no tools block — the agent is working blind');
      dim('  write one: leo agents --auto');
      throw new LeoExit(1);
    }
    const m = new RegExp(BEGIN + ' fingerprint=([a-z0-9]*)').exec(body);
    const have = m ? m[1] : '';
    if (have !== FP) {
      err('AGENTS.md describes a different session than the one you are in');
      dim('  it says ' + have + ', the session is ' + FP);
      dim('  refresh it: leo agents --auto');
      throw new LeoExit(1);
    }
    ok('AGENTS.md matches this session');
    return 0;
  }

  if (mode === 'auto') {
    if (!isFile(agentsFile)) die('no AGENTS.md — run: leo init');
    const generated = block(ctx, adapters, FP);
    const body = readIfFile(agentsFile) || '';

    // Replace between the markers, or append. Everything the developer wrote
    // outside them survives untouched -- AGENTS.md is theirs, and this
    // command owns exactly one section of it.
    let next;
    if (body.indexOf(BEGIN) !== -1) {
      const out = [];
      let skip = false;
      for (const line of body.split('\n')) {
        if (line.indexOf(BEGIN) === 0) {
          skip = true;
          out.push(generated.replace(/\n$/, ''));
          continue;
        }
        if (skip && line.indexOf(END) === 0) { skip = false; continue; }
        if (skip) continue;
        out.push(line);
      }
      next = out.join('\n');
    } else {
      next = body + '\n' + generated;
    }
    writeAtomic(agentsFile, next);

    // Verify what was just written still describes the session, rather than
    // assuming it. An adapter may detect itself from AGENTS.md, so the write
    // can in principle move the answer; if it did, saying so beats shipping a
    // block that `leo agents --check` will reject one command later.
    const after = caps.capFingerprint(ctx, adapters);
    if (after !== FP) {
      warn('writing the block changed what leo detects (' + FP + ' -> ' + after + ')');
      dim('  an adapter is detecting itself from AGENTS.md — run this again,');
      dim("  and if it does not settle, that adapter's present is the bug");
    }

    ok('AGENTS.md updated — ' + FP);
    const b = Buffer.byteLength(readIfFile(agentsFile) || '', 'utf8');
    dim('  AGENTS.md is now ' + b + 'b, and every byte is re-read on every request');
    // The number that matters, stated where the growth happens. 4000 is not a
    // law, it is the point past which somebody should look at what is in here.
    if (b > 4000) warn('AGENTS.md is over 4000b — move detail into .leo/tools/*.md');
    return 0;
  }

  // --- show ---------------------------------------------------------------
  say(block(ctx, adapters, FP).replace(/\n$/, ''));
  return 0;
}

module.exports = { run, isCurrent, BEGIN, END };
