'use strict';
// desc: compile the source tree into one self-contained leo
// usage: leo build [--out <path>]     default: dist/leo.js
//
// The point of this command is vendoring. You clone leo, you build it, and
// you drop the one file it produces into the repository you actually work in
// -- committed, at a revision you can name. The working repo then depends on
// a file it contains rather than on a clone sitting somewhere else on one
// developer's laptop at whatever revision they last pulled.
//
// What it emits is still JavaScript, still commented, still readable.
// "Bundled" here means "one file with no siblings", not "minified". If you
// cannot read the thing you vendored, you have not removed the dependency --
// you have hidden it.
//
// It compiles three things in:
//
//   1. every module under src/, each wrapped as a factory, behind a tiny
//      require shim that resolves the same relative paths the source uses
//   2. the templates, as data
//   3. a __LEO_BUNDLE object carrying the assets, the commands and the
//      built-in adapters, which the seam in src/cli.js picks up instead of
//      reading its own install off disk
//
// No network, and nothing outside the install is read.

const fs = require('fs');
const path = require('path');
const { dim, ok, die } = require('../lib/ui');
const { git } = require('../lib/repo');
const { mkdirp } = require('../lib/fsx');

// Every .js under src/, as ids relative to src/ without the extension:
// 'cli', 'lib/ui', 'cmd/plan', 'integrations/serena'.
function collect(dir, prefix, out) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      collect(full, prefix ? prefix + '/' + e.name : e.name, out);
    } else if (e.name.endsWith('.js')) {
      const id = (prefix ? prefix + '/' : '') + e.name.slice(0, -3);
      out.push({ id, file: full });
    }
  }
  return out;
}

// resolveId — turn a relative require from one module into a bundle id.
// './check' inside cmd/record is cmd/check; '../lib/ui' is lib/ui.
function resolveId(fromId, spec) {
  const base = fromId.indexOf('/') === -1 ? '' : fromId.slice(0, fromId.lastIndexOf('/'));
  const joined = path.posix.normalize(path.posix.join(base, spec));
  return joined.replace(/^\.\//, '');
}

function run(ctx) {
  let out = 'dist/leo.js';
  const argv = ctx.argv.slice();
  while (argv.length) {
    const a = argv.shift();
    if (a === '--out') {
      if (!argv.length) die('--out needs a path');
      out = argv.shift();
    } else if (a[0] === '-') die('unknown option: ' + a);
    else die('unexpected argument: ' + a);
  }
  // Relative to the caller's directory, not to the install: `leo build --out
  // x` should put x where the person typing it is standing.
  if (!path.isAbsolute(out)) out = path.resolve(process.cwd(), out);

  if (ctx.bundle) die('this is a built leo — rebuild from the source clone');

  const srcDir = path.join(ctx.leoHome, 'src');
  const modules = collect(srcDir, '', []);
  if (!modules.length) die('no modules under ' + srcDir + ' — is this a source clone?');

  const ver = ctx.assets.version();
  // The revision this was built from, so a vendored copy can be traced back
  // to a commit. A clone with no git, or a tarball, still builds -- it just
  // cannot say where from, and saying "unknown" is better than refusing.
  const shaR = git(['-C', ctx.leoHome, 'rev-parse', '--short', 'HEAD']);
  const sha = shaR.status === 0 ? shaR.stdout.trim() : 'unknown';
  const dirty = git(['-C', ctx.leoHome, 'diff', '--quiet', 'HEAD']).status === 0 ? '' : '-dirty';

  const L = [];
  L.push('#!/usr/bin/env node');
  L.push("'use strict';");
  L.push('// leo ' + ver + ' — single-file build of ' + sha + dirty);
  L.push('//');
  L.push('// Generated by `leo build`. Do not edit: edit the source tree and');
  L.push('// build again, or your change is lost the next time anyone does.');
  L.push('//');
  L.push('// This file is the whole install. It reads nothing next to itself.');
  L.push('');
  L.push('var __leo_defs = {};');
  L.push('var __leo_cache = {};');
  L.push('');
  L.push('// The require shim. Relative specifiers were resolved to bundle ids at');
  L.push('// build time, so this never touches the filesystem; anything it does not');
  L.push('// know is a Node built-in and goes to the real require.');
  L.push('function __leo_require(id) {');
  L.push('  if (!Object.prototype.hasOwnProperty.call(__leo_defs, id)) return require(id);');
  L.push('  if (__leo_cache[id]) return __leo_cache[id].exports;');
  L.push('  var m = { exports: {} };');
  L.push('  __leo_cache[id] = m;');
  L.push('  __leo_defs[id](m, m.exports, function (s) { return __leo_require(__leo_map[id][s] || s); });');
  L.push('  return m.exports;');
  L.push('}');
  L.push('');

  // The specifier map, per module, so the shim rewrites nothing at runtime.
  const maps = {};
  const bodies = [];
  for (const m of modules) {
    const body = fs.readFileSync(m.file, 'utf8');
    const map = {};
    const re = /require\(\s*'([^']+)'\s*\)/g;
    let mm;
    while ((mm = re.exec(body)) !== null) {
      const spec = mm[1];
      if (spec[0] !== '.') continue;
      map[spec] = resolveId(m.id, spec);
    }
    maps[m.id] = map;
    bodies.push({ id: m.id, body });
  }
  L.push('var __leo_map = ' + JSON.stringify(maps, null, 2) + ';');
  L.push('');

  for (const b of bodies) {
    L.push('// ---------------------------------------------------------------');
    L.push('// src/' + b.id + '.js');
    L.push('__leo_defs[' + JSON.stringify(b.id) + '] = function (module, exports, require) {');
    // Not indented. Reformatting a module body would move every line number
    // in every stack trace away from the source it was built from.
    L.push(b.body);
    L.push('};');
    L.push('');
  }

  // The templates, as data.
  const tmpl = {};
  for (const name of ctx.assets.tmplList()) tmpl[name] = ctx.assets.tmplRead(name);

  L.push('// --------------------------------------------------------- assets --');
  L.push('var __leo_templates = ' + JSON.stringify(tmpl, null, 1) + ';');
  L.push('');
  L.push('global.__LEO_BUNDLE = {');
  L.push('  version: ' + JSON.stringify(ver) + ',');
  L.push('  build: ' + JSON.stringify(sha + dirty) + ',');
  L.push('  assets: {');
  L.push('    version: function () { return ' + JSON.stringify(ver) + '; },');
  L.push('    tmplHas: function (n) { return Object.prototype.hasOwnProperty.call(__leo_templates, n); },');
  L.push('    tmplRead: function (n) { return __leo_templates[n]; },');
  L.push('    tmplList: function () { return Object.keys(__leo_templates); },');
  L.push('  },');

  const cmds = modules.filter((m) => m.id.indexOf('cmd/') === 0).map((m) => m.id.slice(4));
  L.push('  commands: {');
  for (const c of cmds) {
    L.push('    ' + JSON.stringify(c) + ': __leo_require(' + JSON.stringify('cmd/' + c) + '),');
  }
  L.push('  },');

  const ints = modules
    .filter((m) => m.id.indexOf('integrations/') === 0)
    .map((m) => m.id.slice('integrations/'.length))
    .filter((n) => n[0] !== '_');
  L.push('  integrations: {');
  for (const i of ints) {
    L.push('    ' + JSON.stringify(i) + ': __leo_require(' + JSON.stringify('integrations/' + i) + '),');
  }
  L.push('  },');
  L.push('};');
  L.push('');
  L.push('__leo_require(\'cli\').main(process.argv.slice(2));');
  L.push('');

  const body = L.join('\n');

  // Parse it before it is allowed to exist under the name people will run. A
  // bundle that does not compile is worse than no bundle: the failure lands
  // on whoever vendored it, in a repository that is not this one.
  try {
    new (require('vm').Script)(body, { filename: out });
  } catch (e) {
    die('the generated bundle does not parse — this is a bug in leo build: ' + e.message);
  }

  mkdirp(path.dirname(out));
  fs.writeFileSync(out, body);
  fs.chmodSync(out, 0o755);

  const rel = out.startsWith(process.cwd() + path.sep) ? out.slice(process.cwd().length + 1) : out;
  ok('built: ' + rel);
  dim('  leo ' + ver + ' from ' + sha + dirty + ', ' + body.split('\n').length + ' lines');
  dim('  vendor it:  cp "' + out + '" <your repo>/.leo/bin/leo.js');
  return 0;
}

module.exports = { run };
