'use strict';
// desc: keep the companion documents present and current
// usage: leo docs             what exists, what is missing, what is stale
//        leo docs --write     create what is missing, refresh what is generated
//        leo docs --check     non-zero if a document is missing or stale
//
// Five documents, each answering one question, and the split between them is
// the whole design:
//
//   AGENTS.md        how do I work here          every request  — keep it short
//   ARCHITECTURE.md  how do the pieces fit       on demand
//   CODE_REVIEW.md   what does a finding clear   on demand, cycle two
//   RULES.md         what is enforced, and why   on demand
//   SESSION.md       where is this session now   written on every command
//
// One file per question, because a document that answers two of them gets
// read for one and skimmed for the other. The reason AGENTS.md is the short
// one is measured, not aesthetic: it is re-read on every request of every
// session forever, and the other four are opened when somebody needs them.
//
// Two of the five have generated sections -- the tools block in AGENTS.md and
// the rule index in RULES.md -- because both restate something leo already
// knows, and a restatement maintained by hand is a restatement that is wrong.
// SESSION.md is generated whole, by the exit hook, and this command never
// writes it: if it is missing here, that is a bug in leo and saying so is
// more useful than papering over it.

const fs = require('fs');
const path = require('path');
const { info, dim, ok, warn, err, die, head_, LeoExit } = require('../lib/ui');
const { needRepo } = require('../lib/ctx');
const { isFile, isDir, readIfFile, writeAtomic } = require('../lib/fsx');
const caps = require('../lib/caps');
const agentsCmd = require('./agents');

const DOCS = [
  ['AGENTS.md', 'AGENTS.md', 'how to work here'],
  ['CONTEXT.md', 'CONTEXT.md', 'what this project is'],
  ['ARCHITECTURE.md', 'ARCHITECTURE.md', 'how the pieces fit'],
  ['CODE_REVIEW.md', 'review/STANDARDS.md', 'what a finding has to clear'],
  ['RULES.md', 'RULES.md', 'what is enforced, and why'],
];

const RULES_BEGIN = '<!-- leo:rules begin -->';
const RULES_END = '<!-- leo:rules end -->';

// ruleIndex — every rule, its one-line MUST, and its file.
//
// Generated because `.leo/rules/` is the authority and a hand-kept list
// beside it drifts the first time somebody adds a rule in a hurry -- which is
// exactly when a rule gets added.
function ruleIndex(rulesDir) {
  const out = [];
  out.push(RULES_BEGIN);
  out.push('<!-- Generated by `leo docs --write`. Do not edit: run it again. -->');
  out.push('');
  let n = 0;
  const files = isDir(rulesDir)
    ? fs.readdirSync(rulesDir).filter((f) => f.endsWith('.md')).sort()
    : [];
  for (const f of files) {
    const id = f.slice(0, -3);
    if (id === 'EXAMPLE' || id === 'TEMPLATE') continue;
    n++;
    const body = readIfFile(path.join(rulesDir, f)) || '';
    const lines = body.split('\n');
    // The title line, minus its hash. It is written as a MUST or MUST NOT, so
    // it is already the sentence this index wants.
    const t = /^# *(.*)$/.exec(lines[0] || '');
    const title = t ? t[1] : '';
    const hasVerify = lines.some((l) => /^## Verify/.test(l));
    out.push('- **' + id + '** — ' + title +
      (hasVerify ? '' : ' _(no Verify block — leo check skips it)_') +
      '\n  `.leo/rules/' + id + '.md`');
  }
  if (n === 0) out.push('None yet. Write one the next time you fix a real bug.');
  out.push('');
  out.push(RULES_END);
  return out.join('\n') + '\n';
}

// splice — replace a marked block in place, leaving everything the developer
// wrote around it alone.
function splice(file, begin, end, content) {
  const body = readIfFile(file);
  if (body === null) return;
  let next;
  if (body.indexOf(begin) !== -1) {
    const out = [];
    let skip = false;
    for (const line of body.split('\n')) {
      if (line.indexOf(begin) === 0) {
        skip = true;
        out.push(content.replace(/\n$/, ''));
        continue;
      }
      if (skip && line.indexOf(end) === 0) { skip = false; continue; }
      if (skip) continue;
      out.push(line);
    }
    next = out.join('\n');
  } else {
    next = body + '\n' + content;
  }
  writeAtomic(file, next);
}

function run(ctx) {
  needRepo(ctx);
  const adapters = ctx.adapters || caps.loadAdapters(ctx);
  ctx.adapters = adapters;

  let write = false, check = false;
  for (const a of ctx.argv) {
    if (a === '--write') write = true;
    else if (a === '--check') check = true;
    else if (a[0] === '-') die('unknown option: ' + a + '  (--write --check)');
    else die('unexpected argument: ' + a);
  }

  // --- write --------------------------------------------------------------
  if (write) {
    for (const [f, tmpl] of DOCS) {
      const dest = path.join(ctx.root, f);
      if (fs.existsSync(dest)) {
        dim('  keep    ' + f);
      } else if (ctx.assets.tmplHas(tmpl)) {
        fs.writeFileSync(dest, ctx.assets.tmplRead(tmpl));
        info('  write   ' + f);
      } else {
        warn('no template for ' + f);
      }
    }

    const rulesDoc = path.join(ctx.root, 'RULES.md');
    if (!isFile(rulesDoc) && ctx.assets.tmplHas('RULES.md')) {
      fs.writeFileSync(rulesDoc, ctx.assets.tmplRead('RULES.md'));
    }
    if (isFile(rulesDoc)) {
      splice(rulesDoc, RULES_BEGIN, RULES_END, ruleIndex(ctx.rules));
      info('  refresh RULES.md (rule index)');
    }

    // The tools block is `leo agents`' business, not this command's. Calling
    // it rather than reimplementing it is what keeps one answer in one place.
    if (isFile(path.join(ctx.root, 'AGENTS.md'))) {
      let okAgents = true;
      try {
        const sub = Object.create(ctx);
        sub.argv = ['--auto'];
        agentsCmd.run(sub);
      } catch (e) {
        okAgents = false;
      }
      if (okAgents) info('  refresh AGENTS.md (tools block)');
      else warn('could not refresh the AGENTS.md tools block — leo agents --auto');
    }
    process.stderr.write('\n');
  }

  // --- report and check ---------------------------------------------------
  head_('companion documents');
  let missing = 0, stale = 0;
  for (const [f, , q] of DOCS) {
    const there = fs.existsSync(path.join(ctx.root, f));
    info('  ' + f.padEnd(16) + ' ' + (there ? 'ok' : 'MISSING').padEnd(6) + ' ' + q);
    if (!there) missing++;
  }

  if (isFile(path.join(ctx.root, 'SESSION.md'))) {
    info('  ' + 'SESSION.md'.padEnd(16) + ' ' + 'ok'.padEnd(6) + ' written on every leo command');
  } else {
    info('  ' + 'SESSION.md'.padEnd(16) + ' ' + 'MISSING'.padEnd(6) + ' this is a leo bug — report it');
    missing++;
  }

  // Stale is a different failure from missing, and worse: a present document
  // that describes a session nobody is in gets believed.
  const agentsBody = readIfFile(path.join(ctx.root, 'AGENTS.md'));
  if (agentsBody !== null && agentsBody.indexOf('<!-- leo:tools begin') !== -1) {
    if (!agentsCmd.isCurrent(ctx, adapters)) {
      stale++;
      info('  ' + 'AGENTS.md'.padEnd(16) + ' ' + 'STALE'.padEnd(6) + ' tools block — leo agents --auto');
    }
  }

  process.stderr.write('\n');
  if (check) {
    if (missing !== 0 || stale !== 0) {
      err(missing + ' missing, ' + stale + ' stale — leo docs --write');
      throw new LeoExit(1);
    }
    ok('every companion document is present and current');
    return 0;
  }

  if (missing > 0 || stale > 0) {
    dim('  leo docs --write   creates what is missing, refreshes what is generated');
  }
  return 0;
}

module.exports = { run };
