#!/usr/bin/env bash
# desc: write this session's tool and MCP instructions into AGENTS.md
# usage: leo agents                 show the block that belongs in AGENTS.md
#        leo agents --auto          write it, using the mode's own defaults
#        leo agents --ask           the question to put to the developer
#        leo agents --list          every tool leo knows, and its state
#        leo agents --check         non-zero if AGENTS.md is stale or has no block
#
# The problem this solves: `leo session` knows which tools are on, which are
# installed and what each one wants, and the agent never reads any of it,
# because that knowledge lives in a command nobody runs at the moment it
# matters. AGENTS.md is read on every request of every session. So the answer
# goes there.
#
# What goes there is a DIGEST, not the documentation. One row per enabled tool:
# its state, how leo can tell it was used, its MCP names if it has any, the one
# instruction that changes what the agent does, and the path to the rest. The
# full instructions stay in `.leo/tools/<name>.md` and are read on demand.
#
# That split is not a style preference, it is the single most expensive
# decision in this repository. Measurements in .leo/plans/C5-benchmark are why:
# always-loaded bytes are re-read on every turn forever, so seven tool
# documents inlined here would be paid for by every session that needed none of
# them. .leo/rules/ALWAYS-LOADED.md fails the check when this block grows past
# what a digest can justify.
#
# Two ways to decide what is on. `--ask` prints the question for the developer
# and changes nothing; `--auto` takes the mode's defaults, which is what the
# developer already chose when they declared the mode. Neither installs
# anything, and neither turns a capability on: that is `leo session`, and it is
# the developer's.

need_repo

AGENTS="$ROOT/AGENTS.md"
BEGIN='<!-- leo:tools begin'
END='<!-- leo:tools end -->'

_mode=show
while [ $# -gt 0 ]; do
  case "$1" in
    --auto)  _mode=auto;  shift ;;
    --ask)   _mode=ask;   shift ;;
    --list)  _mode=list;  shift ;;
    --check) _mode=check; shift ;;
    -*)      die "unknown option: $1  (--auto --ask --list --check)" ;;
    *)       die "unexpected argument: $1" ;;
  esac
done

# block — the generated section, on stdout. Everything in it is derived: the
# mode, the switches, what is installed, what each adapter says about itself.
# Nothing is stored to make it printable, which is why regenerating it can
# never disagree with `leo session`.
# Computed once, at the top of the run, and used everywhere below. Calling
# cap_fingerprint twice would be the obvious thing and would be wrong: writing
# the block changes AGENTS.md, and an adapter is allowed to detect itself by
# reading AGENTS.md -- ponytail does. Two calls straddling the write can
# therefore disagree, and the block would be stamped with a fingerprint that
# was already out of date before the file was closed.
FP=$(cap_fingerprint)

block() {
  printf '%s fingerprint=%s -->\n' "$BEGIN" "$FP"
  printf '<!-- Generated by `leo agents`. Do not edit: run it again. -->\n'
  printf '\n## Tools this session\n\n'

  if [ -z "${MODE:-}" ]; then
    printf 'No session declared, so nothing is on or off.\n'
    printf 'Ask the developer for one: `leo session --mode coding`.\n'
    printf 'Until then, announce anything you use with `leo use <name>`.\n\n'
    printf '%s\n' "$END"
    return 0
  fi

  printf 'Mode **%s**. Announce every one of these with `leo use <name>`\n' "$MODE"
  printf 'before you use it — that is the line the developer sees and the line\n'
  printf '`leo check` reads, and they cannot drift apart.\n\n'

  _any=0
  printf '| Tool | State | How leo sees it | The one thing to know |\n'
  printf '|---|---|---|---|\n'
  for _c in $CAPS; do
    _st=$(cap_state "$_c")
    _rc=0; cap_present "$_c" >/dev/null 2>&1 || _rc=$?
    _lb=$(cap_label "$_c")
    _kd=$(cap_kind "$_c")

    if [ "$_st" = "on" ] && [ "$_rc" -eq 1 ]; then
      _how="not installed"
      _note="tell the developer: \`leo install $_c\`. Do not install it."
    elif [ "$_st" = "on" ]; then
      case "$_kd" in
        invoked)  _how="\`leo use $_c\`" ;;
        practice) _how="\`leo check\` gates it" ;;
        *)        _how="ambient — no announcement" ;;
      esac
      _note=$(cap_oneline "$_c")
      _m=$(cap_mcp "$_c")
      [ -n "$_m" ] && _note="$_note  MCP: $_m"
      _doc=".leo/tools/$_c.md"
      [ -f "$ROOT/$_doc" ] && _note="$_note  ($_doc)"
    else
      _how="OFF"
      _note="do not use it. \`leo use $_c\` refuses and records the attempt."
    fi
    _any=1
    printf '| %s | %s | %s | %s |\n' "$_lb" "$_st" "$_how" "$_note"
  done
  [ "$_any" -eq 0 ] && printf '| — | — | — | leo knows no tools here |\n'

  printf '\nOFF is the developer'"'"'s decision, not a default to work around.\n'
  printf 'A tool that is ON, installed and never announced fails `leo check`.\n\n'
  printf '%s\n' "$END"
}

case "$_mode" in

  # --- list -------------------------------------------------------------
  # The inventory, for a human. What leo can name, whether it is here, and
  # what it would cost to turn on.
  list)
    head_ "tools leo knows"
    printf '  %-12s %-5s %-10s %-9s %s\n' \
      TOOL STATE INSTALLED KIND MCP >&2
    for _c in $CAPS; do
      _rc=0; cap_present "$_c" >/dev/null 2>&1 || _rc=$?
      case "$_rc" in 0) _in=yes ;; 1) _in=NO ;; *) _in='no-adapter' ;; esac
      _m=$(cap_mcp "$_c"); _m="${_m:--}"
      printf '  %-12s %-5s %-10s %-9s %s\n' \
        "$_c" "$(cap_state "$_c")" "$_in" "$(cap_kind "$_c")" "$_m" >&2
    done
    echo >&2
    dim "  leo agents --ask    put the choice to the developer"
    dim "  leo agents --auto   take the mode's defaults and write AGENTS.md"
    ;;

  # --- ask --------------------------------------------------------------
  # The question, phrased so the agent can paste it and the developer can
  # answer it in one line. leo prints it; it does not ask, and it does not act
  # on an answer it never heard.
  ask)
    [ -n "${MODE:-}" ] || {
      warn "no session yet — the mode decides the defaults"
      dim  "  ask for one first: leo session --mode coding"
    }
    head_ "ask the developer this, before you touch anything"
    info ""
    info "  These tools are available in this repository. Which do you want"
    info "  enabled for this session?"
    info ""
    for _c in $CAPS; do
      _rc=0; cap_present "$_c" >/dev/null 2>&1 || _rc=$?
      case "$_rc" in
        0) _in="installed" ;;
        1) _in="NOT installed — leo install $_c" ;;
        *) _in="leo cannot tell" ;;
      esac
      printf '    %-12s %-4s  %s\n' "$_c" "$(cap_state "$_c")" "$_in" >&2
      _o=$(cap_oneline "$_c")
      [ -n "$_o" ] && printf '                 %s\n' "$_o" >&2
    done
    info ""
    info "  Defaults come from the mode${MODE:+ ($MODE)}. To change one:"
    dim  "    leo session --<name> on|off        <- theirs to run, not yours"
    info ""
    dim  "  They said keep the defaults? Then: leo agents --auto"
    ;;

  # --- check ------------------------------------------------------------
  # The gate. A block that describes a session that no longer exists is worse
  # than no block: the agent reads it, believes it, and uses a tool the
  # developer switched off an hour ago.
  check)
    [ -f "$AGENTS" ] || die "no AGENTS.md — run: leo init"
    grep -q "$BEGIN" "$AGENTS" || {
      err "AGENTS.md has no tools block — the agent is working blind"
      dim "  write one: leo agents --auto"
      exit 1
    }
    _have=$(sed -n "s/.*$BEGIN fingerprint=\([a-z0-9]*\).*/\1/p" "$AGENTS" | head -1)
    _want="$FP"
    if [ "$_have" != "$_want" ]; then
      err "AGENTS.md describes a different session than the one you are in"
      dim "  it says $_have, the session is $_want"
      dim "  refresh it: leo agents --auto"
      exit 1
    fi
    ok "AGENTS.md matches this session"
    ;;

  # --- auto -------------------------------------------------------------
  auto)
    [ -f "$AGENTS" ] || die "no AGENTS.md — run: leo init"
    _tmp=$(mktemp "${TMPDIR:-/tmp}/leo-agents.XXXXXX")
    leo_atexit_add 'rm -f "$_tmp"'

    _new=$(mktemp "${TMPDIR:-/tmp}/leo-block.XXXXXX")
    leo_atexit_add 'rm -f "$_new"'
    block > "$_new"

    # Replace between the markers, or append. Everything the developer wrote
    # outside them survives untouched -- AGENTS.md is theirs, and this command
    # owns exactly one section of it.
    if grep -q "$BEGIN" "$AGENTS"; then
      awk -v b="$BEGIN" -v e="$END" -v f="$_new" '
        index($0, b) == 1 { skip = 1; while ((getline l < f) > 0) print l; close(f); next }
        skip && index($0, e) == 1 { skip = 0; next }
        skip { next }
        { print }' "$AGENTS" > "$_tmp"
    else
      { cat "$AGENTS"; printf '\n'; cat "$_new"; } > "$_tmp"
    fi
    mv "$_tmp" "$AGENTS"

    # Verify what was just written still describes the session, rather than
    # assuming it. An adapter may detect itself from AGENTS.md, so the write
    # can in principle move the answer; if it did, saying so beats shipping a
    # block that `leo agents --check` will reject one command later.
    _after=$(cap_fingerprint)
    if [ "$_after" != "$FP" ]; then
      warn "writing the block changed what leo detects ($FP -> $_after)"
      dim  "  an adapter is detecting itself from AGENTS.md — run this again,"
      dim  "  and if it does not settle, that adapter's _present is the bug"
    fi

    ok "AGENTS.md updated — $FP"
    _b=$(wc -c < "$AGENTS" | tr -d ' ')
    dim "  AGENTS.md is now ${_b}b, and every byte is re-read on every request"
    # The number that matters, stated where the growth happens. 4000 is not a
    # law, it is the point past which somebody should look at what is in here.
    [ "$_b" -gt 4000 ] && warn "AGENTS.md is over 4000b — move detail into .leo/tools/*.md"
    ;;

  # --- show -------------------------------------------------------------
  show)
    block
    ;;
esac
exit 0
