#!/usr/bin/env bash
# desc: compile the source tree into one self-contained leo
# usage: leo build [--out <path>]     default: dist/leo
#
# The point of this command is vendoring. You clone leo, you build it, and you
# drop the one file it produces into the repository you actually work in --
# committed, at a revision you can name. The working repo then depends on a
# file it contains rather than on a clone sitting somewhere else on one
# developer's laptop at whatever revision they last pulled.
#
# What it emits is still bash, still commented, still readable. "Binary" here
# means "one file with no siblings", not "compiled". If you cannot read the
# thing you vendored, you have not removed the dependency -- you have hidden it.
#
# It compiles four things in, in this order, because each needs the last:
#
#   1. LEO_BUNDLED, the version, and the templates -- the assets, which the
#      seam in lib.sh checks for before defining its own file-reading versions.
#   2. lib.sh
#   3. every adapter in core/integrations/, which lib.sh would otherwise glob
#   4. every command in core/cmd/, each wrapped as a function, plus a
#      dispatcher that calls one by name
#
# No network, and nothing outside $LEO_HOME is read.

_out="dist/leo"
while [ $# -gt 0 ]; do
  case "$1" in
    --out) shift; [ $# -gt 0 ] || die "--out needs a path"; _out="$1"; shift ;;
    -*)    die "unknown option: $1" ;;
    *)     die "unexpected argument: $1" ;;
  esac
done

# Relative to the caller's directory, not to $LEO_HOME: `leo build --out x`
# should put x where the person typing it is standing.
case "$_out" in /*) ;; *) _out="$PWD/$_out" ;; esac

_ver=$(leo_version)
# The revision this was built from, so a vendored copy can be traced back to a
# commit. A clone with no git, or a tarball, still builds -- it just cannot say
# where from, and saying "unknown" is better than refusing.
_sha=$(git -C "$LEO_HOME" rev-parse --short HEAD 2>/dev/null || echo unknown)
_dirty=""
git -C "$LEO_HOME" diff --quiet HEAD 2>/dev/null || _dirty="-dirty"

# strip_shebang <file> — everything but the leading #!. A shebang buried inside
# a function body is only a comment, but it reads like a mistake.
strip_shebang() { sed '1{/^#!/d;}' "$1"; }

# The heredoc terminator every embedded template is wrapped in. A template
# containing this string would end its own heredoc and the rest of the file
# would be parsed as code -- so the build refuses rather than emitting a leo
# that is subtly broken.
_term="__LEO_TMPL_EOF__"

# Every file, not just *.md: the vendored skills ship a LICENSE with no
# extension, and MIT requires that notice to travel with the copy. A glob that
# quietly dropped it would make every built leo a licence violation.
_tmpls=$(cd "$LEO_HOME/templates" && find . -type f \
           | sed 's|^\./||' | sort)
[ -n "$_tmpls" ] || die "no templates found in $LEO_HOME/templates"

for _t in $_tmpls; do
  grep -q "$_term" "$LEO_HOME/templates/$_t" \
    && die "template $_t contains the heredoc terminator $_term"
  # A template with no trailing newline would gain one on the way through a
  # heredoc, and the bundle would then install a file that differs from the
  # source tree's by one byte -- which is exactly the failure the equivalence
  # test exists to catch, arriving as a mystery rather than as this message.
  [ -n "$(tail -c1 "$LEO_HOME/templates/$_t")" ] \
    && die "template $_t has no trailing newline"
done

mkdir -p "$(dirname "$_out")"
_tmp=$(mktemp "${TMPDIR:-/tmp}/leo-build.XXXXXX")
trap 'rm -f "$_tmp"' EXIT

{
  # ---------------------------------------------------------- preamble ----
  printf '#!/usr/bin/env bash\n'
  printf '# leo %s — single-file build of %s\n' "$_ver" "$_sha$_dirty"
  printf '#\n'
  printf '# Generated by `leo build`. Do not edit: edit the source tree and\n'
  printf '# build again, or your change is lost the next time anyone does.\n'
  printf '#\n'
  printf '# This file is the whole install. It reads nothing next to itself.\n'
  printf 'set -euo pipefail\n\n'

  # LEO_SELF is what `leo commit` re-execs to run the checks, and in a bundle
  # that has to be this file. Symlink-following is kept: vendored or not,
  # somebody will put a symlink to it on their PATH.
  cat <<'PREAMBLE'
_self="${BASH_SOURCE[0]}"
while [ -L "$_self" ]; do
  _dir=$(cd -P "$(dirname "$_self")" && pwd)
  _self=$(readlink "$_self")
  case "$_self" in /*) ;; *) _self="$_dir/$_self" ;; esac
done
LEO_HOME=$(cd -P "$(dirname "$_self")" && pwd)
LEO_SELF="$_self"
export LEO_HOME LEO_SELF

# Set before lib.sh, which reads it to decide not to define the file-reading
# versions of leo_version, tmpl_has and tmpl_cat.
LEO_BUNDLED=1
export LEO_BUNDLED
PREAMBLE

  printf '\nLEO_VERSION=%s\n' "$_ver"
  printf 'LEO_BUILD=%s\n' "$_sha$_dirty"
  printf 'leo_version() { printf %s "$LEO_VERSION"; }\n\n' "'%s\\n'"

  # --------------------------------------------------------- templates ----
  printf '# --- templates ---------------------------------------------------\n'
  printf '# Compiled in from templates/. `leo init` and `leo task` write these.\n'
  printf 'tmpl_has() {\n  case "$1" in\n'
  for _t in $_tmpls; do printf '    %s) return 0 ;;\n' "$_t"; done
  printf '    *) return 1 ;;\n  esac\n}\n\n'

  printf 'tmpl_cat() {\n  case "$1" in\n'
  for _t in $_tmpls; do
    printf '  %s)\n' "$_t"
    printf 'cat <<%s%s%s\n' "'" "$_term" "'"
    cat "$LEO_HOME/templates/$_t"
    printf '%s\n' "$_term"
    printf '    ;;\n'
  done
  printf '  *) return 1 ;;\n  esac\n}\n\n'

  # --------------------------------------------------------------- lib ----
  printf '# --- lib.sh ------------------------------------------------------\n'
  strip_shebang "$LEO_HOME/core/lib.sh"
  printf '\n'

  # ---------------------------------------------------------- adapters ----
  printf '# --- adapters ----------------------------------------------------\n'
  printf '# Compiled in from core/integrations/. lib.sh globs only the\n'
  printf "# repository's own directory in a bundle; these are already here.\n"
  for _a in "$LEO_HOME"/core/integrations/*.sh; do
    [ -f "$_a" ] || continue
    printf '\n# --- %s ---\n' "$(basename "$_a")"
    strip_shebang "$_a"
  done
  printf '\n'

  # ---------------------------------------------------------- commands ----
  printf '# --- commands ----------------------------------------------------\n'
  printf '# One function per file in core/cmd/. The body is unchanged, so "$1"\n'
  printf '# inside it means what it meant when the file was sourced after a\n'
  printf '# shift -- the dispatcher passes the same arguments along.\n'
  for _c in "$LEO_HOME"/core/cmd/*.sh; do
    [ -f "$_c" ] || continue
    _n=$(basename "$_c" .sh)
    # build is the one command a bundle cannot honour: it compiles a source
    # tree, and a bundle is not one. It gets a stub that says so, rather than
    # being dropped -- "unknown command: build" would send someone hunting for
    # a typo.
    if [ "$_n" = "build" ]; then continue; fi
    printf '\ncmd_%s() {\n' "$_n"
    # Not indented, and not reformatted. Several commands hold a quoted
    # heredoc whose terminator has to stay at column 0; indenting the body
    # turns `EOF` into `  EOF`, the heredoc never closes, and the whole file
    # fails to parse thousands of lines later with "unexpected end of file".
    strip_shebang "$_c"
    printf '}\n'
  done

  cat <<'STUB'

cmd_build() {
  die "this is a built leo ($LEO_BUILD) — rebuild from the source clone"
}
STUB

  # -------------------------------------------------------- dispatcher ----
  cat <<'DISPATCH'

# --- dispatcher ----------------------------------------------------
# Same contract as the source tree's: first argument names the command, the
# rest are its own. Adding a command means adding a file in core/cmd/ and
# building again -- there is still no registry, only a compiled-in one.
cmd="${1:-help}"
[ $# -gt 0 ] && shift

case "$cmd" in
  -h|--help)  cmd=help ;;
  --version)  echo "leo $(leo_version)"; exit 0 ;;
esac

command -v "cmd_$cmd" >/dev/null 2>&1 || die "unknown command: $cmd  (try: leo help)"
"cmd_$cmd" "$@"
DISPATCH
} > "$_tmp"

# Parse it before it is allowed to exist under the name people will run. A
# bundle that does not compile is worse than no bundle: the failure lands on
# whoever vendored it, in a repository that is not this one.
bash -n "$_tmp" || die "the generated bundle does not parse — this is a bug in leo build"

chmod +x "$_tmp"
mv "$_tmp" "$_out"
trap - EXIT

ok "built: ${_out#"$PWD"/}"
dim "  leo $_ver from $_sha$_dirty, $(wc -l < "$_out" | tr -d ' ') lines"
dim "  vendor it:  cp \"$_out\" <your repo>/.leo/bin/leo && git add -f .leo/bin/leo"
