#!/usr/bin/env bash
# desc: keep the companion documents present and current
# usage: leo docs             what exists, what is missing, what is stale
#        leo docs --write     create what is missing, refresh what is generated
#        leo docs --check     non-zero if a document is missing or stale
#
# Five documents, each answering one question, and the split between them is
# the whole design:
#
#   AGENTS.md        how do I work here          every request  — keep it short
#   ARCHITECTURE.md  how do the pieces fit       on demand
#   CODE_REVIEW.md   what does a finding clear   on demand, cycle two
#   RULES.md         what is enforced, and why   on demand
#   SESSION.md       where is this session now   written on every command
#
# One file per question, because a document that answers two of them gets read
# for one and skimmed for the other. The reason AGENTS.md is the short one is
# measured, not aesthetic: it is re-read on every request of every session
# forever, and the other four are opened when somebody needs them.
#
# Two of the five have generated sections -- the tools block in AGENTS.md and
# the rule index in RULES.md -- because both restate something leo already
# knows, and a restatement maintained by hand is a restatement that is wrong.
# SESSION.md is generated whole, by the exit hook in core/lib.sh, and this
# command never writes it: if it is missing here, that is a bug in leo and
# saying so is more useful than papering over it.

need_repo

_write=0; _check=0
while [ $# -gt 0 ]; do
  case "$1" in
    --write) _write=1; shift ;;
    --check) _check=1; shift ;;
    -*)      die "unknown option: $1  (--write --check)" ;;
    *)       die "unexpected argument: $1" ;;
  esac
done

# doc <file> <template> <question it answers>
DOCS="AGENTS.md:AGENTS.md:how to work here
CONTEXT.md:CONTEXT.md:what this project is
ARCHITECTURE.md:ARCHITECTURE.md:how the pieces fit
CODE_REVIEW.md:review/STANDARDS.md:what a finding has to clear
RULES.md:RULES.md:what is enforced, and why"

# --- the rule index -------------------------------------------------------
# Every rule, its one-line MUST, and its file. Generated because `.leo/rules/`
# is the authority and a hand-kept list beside it drifts the first time
# somebody adds a rule in a hurry -- which is exactly when a rule gets added.
rule_index() {
  printf '<!-- leo:rules begin -->\n'
  printf '<!-- Generated by `leo docs --write`. Do not edit: run it again. -->\n\n'
  _n=0
  for _r in "$RULES"/*.md; do
    [ -f "$_r" ] || continue
    _id=$(basename "$_r" .md)
    case "$_id" in EXAMPLE|TEMPLATE) continue ;; esac
    _n=$((_n + 1))
    # The title line, minus its hash. It is written as a MUST or MUST NOT, so
    # it is already the sentence this index wants.
    _t=$(sed -n '1s/^# *//p' "$_r")
    _v=$(awk '/^## Verify/ { print "yes"; exit }' "$_r")
    printf -- '- **%s** — %s%s\n  `.leo/rules/%s.md`\n' \
      "$_id" "$_t" "$([ -z "$_v" ] && printf ' _(no Verify block — leo check skips it)_')" "$_id"
  done
  [ "$_n" -eq 0 ] && printf 'None yet. Write one the next time you fix a real bug.\n'
  printf '\n<!-- leo:rules end -->\n'
}

# splice <file> <begin> <end> <content-file> — replace a marked block in
# place, leaving everything the developer wrote around it alone.
splice() {
  _f="$1"; _b="$2"; _e="$3"; _c="$4"
  _t=$(mktemp "${TMPDIR:-/tmp}/leo-docs.XXXXXX")
  leo_atexit_add 'rm -f "'"$_t"'"'
  if grep -q "$_b" "$_f"; then
    awk -v b="$_b" -v e="$_e" -v f="$_c" '
      index($0, b) == 1 { skip = 1; while ((getline l < f) > 0) print l; close(f); next }
      skip && index($0, e) == 1 { skip = 0; next }
      skip { next }
      { print }' "$_f" > "$_t"
  else
    { cat "$_f"; printf '\n'; cat "$_c"; } > "$_t"
  fi
  mv "$_t" "$_f"
}

_missing=0; _stale=0

# --- write ----------------------------------------------------------------
if [ "$_write" -eq 1 ]; then
  printf '%s\n' "$DOCS" | while IFS=: read -r _f _tmpl _q; do
    [ -n "$_f" ] || continue
    if [ -e "$ROOT/$_f" ]; then
      dim "  keep    $_f"
    elif tmpl_has "$_tmpl"; then
      tmpl_cat "$_tmpl" > "$ROOT/$_f"
      info "  write   $_f"
    else
      warn "no template for $_f"
    fi
  done

  [ -f "$ROOT/RULES.md" ] || { tmpl_has RULES.md && tmpl_cat RULES.md > "$ROOT/RULES.md"; }
  if [ -f "$ROOT/RULES.md" ]; then
    _ri=$(mktemp "${TMPDIR:-/tmp}/leo-rules.XXXXXX")
    leo_atexit_add 'rm -f "'"$_ri"'"'
    rule_index > "$_ri"
    splice "$ROOT/RULES.md" '<!-- leo:rules begin -->' '<!-- leo:rules end -->' "$_ri"
    info "  refresh RULES.md (rule index)"
  fi

  # The tools block is `leo agents`' business, not this command's. Calling it
  # rather than reimplementing it is what keeps one answer in one place.
  if [ -f "$ROOT/AGENTS.md" ]; then
    bash "$LEO_SELF" agents --auto >/dev/null 2>&1 \
      && info "  refresh AGENTS.md (tools block)" \
      || warn "could not refresh the AGENTS.md tools block — leo agents --auto"
  fi
  echo >&2
fi

# --- report and check -----------------------------------------------------
head_ "companion documents"
printf '%s\n' "$DOCS" | while IFS=: read -r _f _tmpl _q; do
  [ -n "$_f" ] || continue
  if [ -e "$ROOT/$_f" ]; then
    printf '  %-16s %-6s %s\n' "$_f" "ok" "$_q" >&2
  else
    printf '  %-16s %-6s %s\n' "$_f" "MISSING" "$_q" >&2
  fi
done

# The loop above runs in a subshell (it is the right-hand side of a pipe), so
# a counter incremented inside it is lost on the way out. Counted again here,
# in this shell, rather than restructured: the display wants a stream and the
# tally wants a variable, and two small passes are cheaper to read than one
# clever one.
for _f in AGENTS.md CONTEXT.md ARCHITECTURE.md CODE_REVIEW.md RULES.md; do
  [ -e "$ROOT/$_f" ] || _missing=$((_missing + 1))
done

if [ -f "$ROOT/SESSION.md" ]; then
  printf '  %-16s %-6s %s\n' "SESSION.md" "ok" "written on every leo command" >&2
else
  printf '  %-16s %-6s %s\n' "SESSION.md" "MISSING" "this is a leo bug — report it" >&2
  _missing=$((_missing + 1))
fi

# Stale is a different failure from missing, and worse: a present document that
# describes a session nobody is in gets believed.
if [ -f "$ROOT/AGENTS.md" ] && grep -q '<!-- leo:tools begin' "$ROOT/AGENTS.md"; then
  bash "$LEO_SELF" agents --check >/dev/null 2>&1 || {
    _stale=$((_stale + 1))
    printf '  %-16s %-6s %s\n' "AGENTS.md" "STALE" "tools block — leo agents --auto" >&2
  }
fi

echo >&2
if [ "$_check" -eq 1 ]; then
  [ "$_missing" -eq 0 ] && [ "$_stale" -eq 0 ] || {
    err "$_missing missing, $_stale stale — leo docs --write"
    exit 1
  }
  ok "every companion document is present and current"
  exit 0
fi

[ "$_missing" -gt 0 ] || [ "$_stale" -gt 0 ] \
  && dim "  leo docs --write   creates what is missing, refreshes what is generated"
exit 0
